
spring:
  application:
    name: schedule
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/inclination?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
  instance:
    prefer-ip-address: true

# hystrix����
# ��ʹʹ�����������Ӧ�ķ�������Ҫʹ��@HystrixCommandע��
hystrix:
  command:
    # default ��ʾȫ�ֵģ�Ĭ�ϵ�����
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    # ������������ض��ķ���
#    getProductInfoList:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000

# ͨ��feign����������hystrix-coreʵ��hystrix����
feign:
  hystrix:
    enabled: true

# �Զ���
inclination:
  duration: 10000
server:
  port: 9701
